# Generated by Django 4.2.4 on 2023-09-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_slag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slag',
            new_name='slug',
        ),
    ]
