# Generated by Django 4.2.4 on 2023-09-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company')),
                ('suptitle', models.TextField(max_length=500)),
                ('fasebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('phones', models.TextField(blank=True, max_length=20, null=True)),
                ('email', models.TextField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('android_app', models.URLField(blank=True, null=True)),
                ('ios_app', models.URLField(blank=True, null=True)),
                ('call_us', models.CharField(max_length=100)),
                ('email_us', models.CharField(max_length=100)),
            ],
        ),
    ]
