# Generated by Django 4.2.4 on 2023-10-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_code_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='2AP1MR85', max_length=10),
        ),
    ]
